//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string @event { get; set; }
        public long auditable_id { get; set; }
        public string auditable_type { get; set; }
        public string old_values { get; set; }
        public string new_values { get; set; }
        public string url { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
        public string tags { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
