//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallery_lang_contents
    {
        public long id { get; set; }
        public Nullable<long> gallery_id { get; set; }
        public Nullable<long> lang_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string html_title { get; set; }
        public string html_description { get; set; }
        public string html_keywords { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
