//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_logs
    {
        public long id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string ip { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string isp { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string timezone { get; set; }
        public string region_name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
