//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_refresh_tokens
    {
        public string id { get; set; }
        public string access_token_id { get; set; }
        public bool revoked { get; set; }
        public Nullable<System.DateTime> expires_at { get; set; }
    }
}
