//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class owner_members
    {
        public long id { get; set; }
        public Nullable<long> owner_id { get; set; }
        public string full_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string cast { get; set; }
        public string profession { get; set; }
        public string profession_position { get; set; }
        public string religion { get; set; }
        public string education { get; set; }
        public string living_place { get; set; }
        public string abroad_occupation { get; set; }
        public Nullable<int> health_condition { get; set; }
        public string physical_disability_condition { get; set; }
        public Nullable<int> marriage_status { get; set; }
        public Nullable<int> language { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
