//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public long id { get; set; }
        public string meta_title { get; set; }
        public string meta_keywords { get; set; }
        public string meta_descriptions { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string mobile_no { get; set; }
        public string email { get; set; }
        public string public_email { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string fb_link { get; set; }
        public string twitter_link { get; set; }
        public string youtube_link { get; set; }
        public string skype_link { get; set; }
        public string instagram_link { get; set; }
        public string main_title { get; set; }
        public string secondary_title { get; set; }
        public string time_zone { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
