//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_house_senior_details
    {
        public int senior_id { get; set; }
        public string Home_no { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string image_path { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Contact_no { get; set; }
        public System.DateTime DOB { get; set; }
        public string BirthPlace { get; set; }
        public string Gender { get; set; }
        public string currentliving { get; set; }
        public string health { get; set; }
        public string religion { get; set; }
        public string CitizenShip_no { get; set; }
        public string CitizenshipIssue_district { get; set; }
        public System.DateTime citizenissue_date { get; set; }
        public string Name { get; set; }
        public string uttardata_naam { get; set; }
    }
}
