//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_house_details
    {
        public long id { get; set; }
        public int ghar_number { get; set; }
        public string old_gabisa { get; set; }
        public int old_ward_number { get; set; }
        public string tole { get; set; }
        public double house_latitude { get; set; }
        public double house_longitude { get; set; }
        public string code { get; set; }
        public string house_owner_name { get; set; }
        public int total_house_member { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
