//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_house_owner_infos
    {
        public long id { get; set; }
        public int ghar_number { get; set; }
        public string full_name { get; set; }
        public string education { get; set; }
        public string profession { get; set; }
        public int mobile_number { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string birth_place { get; set; }
        public string gender { get; set; }
        public string temporary_address { get; set; }
        public string health { get; set; }
        public string religion { get; set; }
        public int citizenship_number { get; set; }
        public System.DateTime citizenship_release_date { get; set; }
        public string citizenship_release_district { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
