//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smarttechgolanchaur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public bool status { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string ip { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<int> security { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public string permissions { get; set; }
        public string remember_token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string image { get; set; }
        public string verification_code { get; set; }
        public string global_setting { get; set; }
    }
}
